### ISSUE TITLE
Need country code DE

### ISSUE THREAD

**Issue by Titanius** [alessandro893/MacOS-WLAN-Driver#1]
Hello I need the country code DE for 10.12.5

**Comment by alessandro893** [comment]
AirPortBrcm4360 or AirPortBrcm4331?

**Comment by Titanius** [comment]
4360

Am 07.06.2017 um 18:52 schrieb alessandro893 <notifications@github.com<mailto:notifications@github.com>>:


AirPortBrcm4360 or AirPortBrcm4331?

**Comment by alessandro893** [comment]
Done, test it please!

(2402 - 2472 @ 40), 30dbm
(5170 - 5250 @ 80), 24dbm
(5250 - 5330 @ 80), 24dbm
(5490 - 5730 @ 160), 24dbm
(5735 - 5835 @ 80), 30dbm
