### ISSUE TITLE
Country Code #a

### ISSUE THREAD

**Issue by Mateo1234454545** [alessandro893/MacOS-WLAN-Driver#14]
Hi.
Is it possible to make a patch with country code #a instead of US , for Catalina 10.15.1 ?

Thanks in advance.

**Comment by alessandro893** [comment]
Hello! Sorry, but “#a” country code is deprecated and removed from macos driver since 10.13.0

**Comment by Mateo1234454545** [comment]
Oh, I see.
Is it possible then a patch with country code GR ?
i'm asking because I'm in Greece and US country code doesn't show channels 12 and 13.

**Comment by alessandro893** [comment]
> Oh, I see.
> Is it possible then a patch with country code GR ?
> i'm asking because I'm in Greece and US country code doesn't show channels 12 and 13.

Yes it's possible to change ccode to "GR". But did you try to test my driver? My mac works with channels 12,13 and "US" ccode.

![alt text](https://raw.githubusercontent.com/alessandro893/MacOS-WLAN-Driver/master/img/sys_report.png)
![alt text](https://raw.githubusercontent.com/alessandro893/MacOS-WLAN-Driver/master/img/channel_13.png)

**Comment by Mateo1234454545** [comment]
That's strange.
After using your tool in Catalina I don't have 12,13 channels.
[Screen Shot 2019-11-05 at 14.02.56.pdf](https://github.com/alessandro893/MacOS-WLAN-Driver/files/3808894/Screen.Shot.2019-11-05.at.14.02.56.pdf)

**Comment by alessandro893** [comment]
> That's strange.
> After using your tool in Catalina I don't have 12,13 channels.
> [Screen Shot 2019-11-05 at 14.02.56.pdf](https://github.com/alessandro893/MacOS-WLAN-Driver/files/3808894/Screen.Shot.2019-11-05.at.14.02.56.pdf)

Run this app:
[Wlan fix (GR).zip](https://github.com/alessandro893/MacOS-WLAN-Driver/files/3810278/Wlan.fix.GR.zip)

**Comment by Mateo1234454545** [comment]
Working great.
Thank you!!!
