### ISSUE TITLE
2.4 GHZ Country Code Europe

### ISSUE THREAD

**Issue by sector1979** [alessandro893/MacOS-WLAN-Driver#17]
Hello.

Can you modify 2.4 GHZ Country Code too ?  
I need to connect to Channel 13 but my Wifi card from System Info tell me that channel 11 is my last available channel ( maybe US configuration ? ) 

I live in Italy

**Comment by alessandro893** [comment]
Hello. I just released new version with possibility to set ANY country code via input form.

[https://github.com/alessandro893/MacOS-WLAN-Driver/releases/latest](url)

![alt text](https://raw.githubusercontent.com/alessandro893/MacOS-WLAN-Driver/master/img/cc_input.png)

**Comment by sector1979** [comment]
thank you Alessandro i love you.  Marry Christmas !!!
