### ISSUE TITLE
Does it work with MacBook pro 16 inch?

### ISSUE THREAD

**Issue by xDaKillerx** [alessandro893/MacOS-WLAN-Driver#21]
So I'm currently using MBA 2014 and it is working nicely. So I was planning to upgrade to MBP 16 inch and was wondering if it's patchable using this tool? Thank you. I've searched and I think it's the same chip as mbp 13 inch 2018 2019.

**Comment by alessandro893** [comment]
Try different solution - https://github.com/acidanthera/AirportBrcmFixup
