### ISSUE TITLE
configuration is going back after installation 

### ISSUE THREAD

**Issue by amithacoon** [alessandro893/MacOS-WLAN-Driver#23]
hey, I'm using the patch over Catalina with MacBook Pro. (after csrutil disabled) and the status is disabled 

after 30-40 min of the new configuration its seems like the MacBook going back to the old configuration

**Comment by amithacoon** [comment]
any solution? sorry but either way I install the configuration is going back to IL

**Comment by alessandro893** [comment]
> any solution? sorry but either way I install the configuration is going back to IL

Catalina? Broadcom 4360?

**Comment by amithacoon** [comment]
Catalina, Im not sure what type. I have MacBook Pro 2018

**Comment by alessandro893** [comment]
> Catalina, Im not sure what type. I have MacBook Pro 2018

This driver is incompatible with your Macbook. Try different solution - https://github.com/acidanthera/AirportBrcmFixup

**Comment by amithacoon** [comment]
tnx!
