### ISSUE TITLE
Big Sur compatibility

### ISSUE THREAD

**Issue by vrslev** [alessandro893/MacOS-WLAN-Driver#26]
Hello! Are you planning to make patch work on Big Sur?

**Comment by tdubinin** [comment]
Hello! Any news?

**Comment by alessandro893** [comment]
Hello, can't continue developing (don't have Big Sur compatible Mac), My Mac (MBP early 2013) lags very much with Big Sur, performed downgrade to Catalina. Earlier when I tried install own kext to system partition (with mounting root as RW, creating snapshot), I get bootloop, without ability to enter recovery mode.

**Comment by IVPXS** [comment]
Any news about Big Sur compatibility? Vanilla wifi driver is throttling my 5GHz connection, apparently :(
